import { DivContainerSVG, SVGContent } from '../theme';

export default function MenuIcon() {
    return (
        <DivContainerSVG>
            <SVGContent viewBox='0 0 512 512'>
                <rect
                    height='80'
                    width='80'
                    fill='none'
                    rx='40'
                    ry='40'
                    stroke='#f9f7db'
                    strokeWidth='32'
                    x='64'
                    y='64'
                />
                <rect
                    height='80'
                    width='80'
                    fill='none'
                    rx='40'
                    ry='40'
                    stroke='#f9f7db'
                    strokeWidth='32'
                    x='216'
                    y='64'
                />
                <rect
                    height='80'
                    width='80'
                    fill='none'
                    rx='40'
                    ry='40'
                    stroke='#f9f7db'
                    strokeWidth='32'
                    x='368'
                    y='64'
                />
                <rect
                    height='80'
                    width='80'
                    fill='none'
                    rx='40'
                    ry='40'
                    stroke='#f9f7db'
                    strokeWidth='32'
                    x='64'
                    y='216'
                />
                <rect
                    height='80'
                    width='80'
                    fill='none'
                    rx='40'
                    ry='40'
                    stroke='#f9f7db'
                    strokeWidth='32'
                    x='216'
                    y='216'
                />
                <rect
                    height='80'
                    width='80'
                    fill='none'
                    rx='40'
                    ry='40'
                    stroke='#f9f7db'
                    strokeWidth='32'
                    x='368'
                    y='216'
                />
                <rect
                    height='80'
                    width='80'
                    fill='none'
                    rx='40'
                    ry='40'
                    stroke='#f9f7db'
                    strokeWidth='32'
                    x='64'
                    y='368'
                />
                <rect
                    height='80'
                    width='80'
                    fill='none'
                    rx='40'
                    ry='40'
                    stroke='#f9f7db'
                    strokeWidth='32'
                    x='216'
                    y='368'
                />
                <rect
                    height='80'
                    width='80'
                    fill='none'
                    rx='40'
                    ry='40'
                    stroke='#f9f7db'
                    strokeWidth='32'
                    x='368'
                    y='368'
                />
            </SVGContent>
        </DivContainerSVG>
    );
}

